name: usb_serial_scanners
description: "A new Flutter plugin project."
version: 0.1.3+2025032701
# homepage:
publish_to: "none"

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  usb_serial:
    git:
      url: https://github.com/jymden/usbserial.git
      ref: master
  shared_preferences: ^2.3.4
  qr_flutter: ^4.1.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
# flutter:
